Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import fsspec
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import scipy.spatial
import numpy as np
import geoviews as gv
from geoviews import opts
from pyproj import Transformer
from holoviews.operation.datashader import rasterize
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m~/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/dask/dataframe/__init__.py:97[0m
[1;32m     96[0m [38;5;28;01mif[39;00m _dask_expr_enabled():
[0;32m---> 97[0m     [38;5;28;01mimport[39;00m [38;5;21;01mdask_expr[39;00m [38;5;28;01mas[39;00m [38;5;21;01mdd[39;00m
[1;32m     99[0m     [38;5;66;03m# trigger loading of dask-expr which will in-turn import dask.dataframe and run remainder[39;00m
[1;32m    100[0m     [38;5;66;03m# of this module's init updating attributes to be dask-expr[39;00m
[1;32m    101[0m     [38;5;66;03m# note: needs reload, in case dask-expr imported before dask.dataframe; works fine otherwise[39;00m

[0;31mModuleNotFoundError[0m: No module named 'dask_expr'

The above exception was the direct cause of the following exception:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 11[0m
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgeoviews[39;00m [38;5;28;01mimport[39;00m opts
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyproj[39;00m [38;5;28;01mimport[39;00m Transformer
[0;32m---> 11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mholoviews[39;00m[38;5;21;01m.[39;00m[38;5;21;01moperation[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatashader[39;00m [38;5;28;01mimport[39;00m rasterize

File [0;32m~/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/holoviews/operation/datashader.py:5[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcollections[39;00m[38;5;21;01m.[39;00m[38;5;21;01mabc[39;00m [38;5;28;01mimport[39;00m Callable, Iterable
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mfunctools[39;00m [38;5;28;01mimport[39;00m partial
[0;32m----> 5[0m [38;5;28;01mimport[39;00m [38;5;21;01mdask[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdataframe[39;00m [38;5;28;01mas[39;00m [38;5;21;01mdd[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mdatashader[39;00m [38;5;28;01mas[39;00m [38;5;21;01mds[39;00m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mdatashader[39;00m[38;5;21;01m.[39;00m[38;5;21;01mreductions[39;00m [38;5;28;01mas[39;00m [38;5;21;01mrd[39;00m

File [0;32m~/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/dask/dataframe/__init__.py:110[0m
[1;32m    103[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m e:
[1;32m    104[0m     msg [38;5;241m=[39m (
[1;32m    105[0m         [38;5;124m"[39m[38;5;124mDask dataframe requirements are not installed.[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    106[0m         [38;5;124m"[39m[38;5;124mPlease either conda or pip install as follows:[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    107[0m         [38;5;124m"[39m[38;5;124m  conda install dask                     # either conda install[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    108[0m         [38;5;124m'[39m[38;5;124m  python -m pip install [39m[38;5;124m"[39m[38;5;124mdask[dataframe][39m[38;5;124m"[39m[38;5;124m --upgrade  # or python -m pip install[39m[38;5;124m'[39m
[1;32m    109[0m     )
[0;32m--> 110[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m    113[0m [38;5;28;01mif[39;00m _dask_expr_enabled():
[1;32m    114[0m     [38;5;28;01mtry[39;00m:

[0;31mImportError[0m: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install

