Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/ERA5_interactive/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
w_time = pn.widgets.IntSlider(name='Year', start=0, end=83)
w_var = pn.widgets.Select(name='Data Variable', options=list(xrds.data_vars))

dataset_controls = pn.WidgetBox(
                                '## Dataset Controls', 
                                w_var, 
                                )
dataset_controls
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m w_time [38;5;241m=[39m [43mpn[49m[38;5;241m.[39mwidgets[38;5;241m.[39mIntSlider(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mYear[39m[38;5;124m'[39m, start[38;5;241m=[39m[38;5;241m0[39m, end[38;5;241m=[39m[38;5;241m83[39m)
[1;32m      2[0m w_var [38;5;241m=[39m pn[38;5;241m.[39mwidgets[38;5;241m.[39mSelect(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mData Variable[39m[38;5;124m'[39m, options[38;5;241m=[39m[38;5;28mlist[39m(xrds[38;5;241m.[39mdata_vars))
[1;32m      4[0m dataset_controls [38;5;241m=[39m pn[38;5;241m.[39mWidgetBox(
[1;32m      5[0m                                 [38;5;124m'[39m[38;5;124m## Dataset Controls[39m[38;5;124m'[39m, 
[1;32m      6[0m                                 w_var, 
[1;32m      7[0m                                 )

[0;31mNameError[0m: name 'pn' is not defined

